services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  AwsLightsailBundle\Client\:
    resource: '../../Client/'
  AwsLightsailBundle\Command\:
    resource: '../../Command/'
  AwsLightsailBundle\Controller\:
    resource: '../../Controller/'
  AwsLightsailBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  AwsLightsailBundle\Repository\:
    resource: '../../Repository/'
  AwsLightsailBundle\Service\:
    resource: '../../Service/'
